### ISSUE TITLE
Are those Warning in logs safe to ignore?

### ISSUE THREAD

**Issue by JDA88** [snmptt/snmptt#11] opened 2022-08-22 13:04 UTC
**Used version:** 1.5 Beta 1 in Windows

While running `snmptt` I have some message in the logs that I fail to identify as “expected” or real issues.
Traps are handled correctly but I want to be sure I can ignore those messages before going into production.

First message:

- `No such signal: SIGUSR1 at snmptt line 767`
  - I get this message once every time I start the program
- Second message `Use of uninitialized value`, I get a bunch of those every time I receive a trap (examples bellow)
  - `Use of uninitialized value $variable_fix in numeric eq (==) at snmptt line 3633, <$fh_FILE> line 5.`
  - `Use of uninitialized value $variable_fix in numeric eq (==) at snmptt line 3633, <$fh_FILE> line 6.`
  - `Use of uninitialized value $variable_fix in numeric eq (==) at snmptt line 3633, <$fh_FILE> line 7.`
  - `Use of uninitialized value $variable_fix in numeric eq (==) at snmptt line 3633, <$fh_FILE> line 8.`
  - `Use of uninitialized value $right in reverse at snmptt line 2972, <$fh_FILE> line 8.`
  - `Use of uninitialized value $format_line in string at snmptt line 2770, <$fh_FILE> line 8.`
  - `Use of uninitialized value $t_time in string eq at snmptt line 7162.`
  - `Use of uninitialized value $right in reverse at snmptt line 2972.`
  - `Use of uninitialized value $format_line in string at snmptt line 2770.`
  - `Use of uninitialized value $receivedtrap in pattern match (m//) at snmptt line 2663.`
  - `Use of uninitialized value $_ in pattern match (m//) at snmptt line 2687.`

If you want me to enable debugging to get information that is more detailed I can obviously help.

**Comment by AlexB7** [comment] 2022-08-22 14:55
I have fixed 'No such signal'.

For 'uninitialized value', can you send me a debug log?  I can fix the issue at each of the lines above but I'd rather fix it at the source.  I assume this is only happening with a specific (bad) trap so I can fix this when the trap is read.

**Comment by JDA88** [comment] 2022-08-22 15:05
I have enable the debug logs and I will let it run a few hours.
Part of the `uninitialized` errors come if `snmptt` tries to write to the Statistics table before handling a trap (that make sense). The rest comes from tests or normal traps.

The log will contain sensitive information’s. Do I have to obfuscate them of is there a safe way to share that with you without uploading it in public to GitHub?

**Comment by JDA88** [comment] 2022-08-23 06:10
First batch of log is very easy to reproduce. Start `snmptt` with a low `statistics_interval` value and as soon as he will try to write to the statistics table (before it received a trap) wou will get the following warnings:
```
Use of uninitialized value $right in reverse at snmptt line 2972.
Use of uninitialized value $right in reverse at snmptt line 2972.
Use of uninitialized value $right in reverse at snmptt line 2972.
Use of uninitialized value $right in reverse at snmptt line 2972.
Use of uninitialized value $right in reverse at snmptt line 2972.
Use of uninitialized value $right in reverse at snmptt line 2972.
Use of uninitialized value $right in reverse at snmptt line 2972.
Use of uninitialized value $right in reverse at snmptt line 2972.
Use of uninitialized value $right in reverse at snmptt line 2972.
Use of uninitialized value $right in reverse at snmptt line 2972.
Use of uninitialized value $right in reverse at snmptt line 2972.
Use of uninitialized value $var[6] in pattern match (m//) at snmptt line 2564.
Use of uninitialized value $right in reverse at snmptt line 2972.
Use of uninitialized value $right in reverse at snmptt line 2972.
Use of uninitialized value $right in reverse at snmptt line 2972.
Use of uninitialized value $right in reverse at snmptt line 2972.
Use of uninitialized value $right in reverse at snmptt line 2972.
Use of uninitialized value $right in reverse at snmptt line 2972.
Use of uninitialized value $right in reverse at snmptt line 2972.
Use of uninitialized value $right in reverse at snmptt line 2972.
Use of uninitialized value $right in reverse at snmptt line 2972.
Use of uninitialized value $right in reverse at snmptt line 2972.
Use of uninitialized value $right in reverse at snmptt line 2972.
Use of uninitialized value $right in reverse at snmptt line 2972.
Use of uninitialized value $right in reverse at snmptt line 2972.
Use of uninitialized value $right in reverse at snmptt line 2972.
Use of uninitialized value $right in reverse at snmptt line 2972.
Use of uninitialized value $right in reverse at snmptt line 2972.
Use of uninitialized value $receivedtrap in pattern match (m//) at snmptt line 2663.
Use of uninitialized value $_ in pattern match (m//) at snmptt line 2687.
Use of uninitialized value $right in reverse at snmptt line 2972.
Use of uninitialized value $format_line in string at snmptt line 2770.
```

**Comment by AlexB7** [comment] 2022-08-23 10:36
The custom DB column for statistics would be causing this.  I'll review and get back to you.  Once this is fixed we can look at the others.

**Comment by AlexB7** [comment] 2022-08-23 10:52
The warnings related to `statistics_interval` should be fixed.  The only variable substitutions that will be run for the custom SQL statistics column is now:

$Fa - alarm (bell) (BEL)
$Ff - form feed (FF)
$Fn - newline (LF, NL)
$Fr - return (CR)
$Ft - tab (HT, TAB)
$H - Host name of the system running SNMPTT
$$ - Print a $

**Comment by JDA88** [comment] 2022-08-23 11:04
Just tested with the last version:
`No such signal` is indeed gone!
Same scenario, start `snmptt` with a small `statistics_interval` value and as soon as he will try to write to the statistics table (before it received a trap) I get following warnings:
```
Use of uninitialized value $t_time in string eq at snmptt line 7195.
Performing substitution on custom column: custom_static_string
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $var[6] in pattern match (m//) at snmptt line 2597.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $receivedtrap in pattern match (m//) at snmptt line 2696.
Use of uninitialized value $_ in pattern match (m//) at snmptt line 2720.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $format_line in string at snmptt line 2803.
Done performing substitution on custom column: custom_static_string
Performing substitution on custom column: $H
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $var[6] in pattern match (m//) at snmptt line 2597.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $receivedtrap in pattern match (m//) at snmptt line 2696.
Use of uninitialized value $_ in pattern match (m//) at snmptt line 2720.
Use of uninitialized value $right in reverse at snmptt line 3005.
Use of uninitialized value $format_line in string at snmptt line 2803.
Done performing substitution on custom column: HOSTNAME
```



My `sql_custom_columns_statistics` look like this
```
sql_custom_columns_statistics = <<END
ts_source
custom_static_string
ts_hostname
$H
END
```

**Comment by AlexB7** [comment] 2022-08-23 11:45
I missed a few spots in the code..  Can you try again?

**Comment by JDA88** [comment] 2022-08-23 11:56
> I missed a few spots in the code.. Can you try again?

Much better, the only one left now is this one:
`Use of uninitialized value $t_time in string eq at snmptt line 7195.`

May I suggest logging something like this:
```
Custom column [column_name] substitution [$variable] by [value]
```
Instead of:
```
Performing substitution on custom column: $H
Done performing substitution on custom column: HOSTNAME
```
That would make the log much more readable

**Comment by AlexB7** [comment] 2022-08-23 12:13
Does the `uninitialized value $t_time` only appear when it tries to write the statistics table before any traps are received?

**Comment by JDA88** [comment] 2022-08-23 12:17
No, it appear in both scenario:
- When writing to the statistics table before receiving a trap (every time it tries to write to the table)
- When writing to the statistics table after receiving a trap (every time it tries to write to the table)

**Comment by AlexB7** [comment] 2022-08-23 12:25
I made another change.  Please test and also make sure the dates are correct.

**Comment by JDA88** [comment] 2022-08-23 12:37
It works now, the messages are gone. I use the following date format, and the SQL INSERT work.
```
date_time_format_sql = %Y-%m-%dT%H:%M:%S
stat_time_format_sql = %Y-%m-%dT%H:%M:%S
```

For the others (message when receiving traps), when I send a test trap:
```
EVENT coldStart .1.3.6.1.6.3.1.1.5.1 "LOGONLY" Warning
FORMAT Device reinitialized (coldStart)
```

I get the messages:
```
Use of uninitialized value $right in reverse at snmptt line 3005, <$fh_FILE> line 8.
Use of uninitialized value $right in reverse at snmptt line 3005, <$fh_FILE> line 8.
Use of uninitialized value $right in reverse at snmptt line 3005, <$fh_FILE> line 8.
Use of uninitialized value $format_line in string at snmptt line 2803, <$fh_FILE> line 8.
```

**Comment by AlexB7** [comment] 2022-08-23 22:00
I'm not able to reproduce the issue.  Can you remove confidential info and email the debug log to me?  Email address is in the docs under License / copyright.

**Comment by JDA88** [comment] 2022-08-24 08:11
I will do this!

**Comment by AlexB7** [comment] 2022-08-24 16:10
I haven't received your email. Can you send a test email with no attachments?  The SF forwarder seems to be dropping emails.

**Comment by JDA88** [comment] 2022-08-24 16:18
You are right i have a not delivered message with <mx.sourceforge.net #4.0.0 smtp; 550 Blacklisted file extension detected>'
I just re-sent it and renamed the file to see if it pass the filter..

**Comment by AlexB7** [comment] 2022-08-24 22:06
Can you please test again with the latest from git?

**Comment by JDA88** [comment] 2022-08-25 06:27
It works perfectly, no more uninitialized messages!

Unfortunately as we are still in the implementation phase the volume and type of trap is pretty limited so I can’t say if there is still some edge case where the message could appear.
I will let you know if I have new ones!

Thanks you again

**Closed** 2022-08-25 10:47 UTC
